Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

#My Solution
#O(n) Time and O(n) Space
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        mappings = defaultdict(int)
        
        for char in s:
            mappings[char] += 1
        
        for char in t:
            mappings[char] -= 1
            
        for char in mappings:
            if mappings[char] == -1 or mappings[char] > 0:
                return char

#Shorter syntax
#O(n) Time and O(1) Space
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for l in t:
	        if t.count(l) > s.count(l): return l
            